export const ACTION = {
    //Authentication

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGOUT: 'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',
    ADD_PHONE_NUMBER: 'ADD_PHONE_NUMBER',
    ADD_BVN: 'ADD_BVN',
    BVN_VALIDATION: 'BVN_VALIDATION',
    SIGN_UP_OTP_VALIDATION: 'SIGN_UP_OTP_VALIDATION',
    SIGN_UP_OTP_VALIDATION_REQUEST: 'SIGN_UP_OTP_VALIDATION_REQUEST',
    GENERATE_USER_REQUEST: 'GENERATE_USER_REQUEST',
    GENERATE_USER:'GENERATE_USER',
    GENERATE_USER_SUCCESS:'GENERATE_USER_SUCCESS',

   
};
export const REG_EXPRESSION={
    
     EMAIL:/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/,
     PASSWORD: /^[a-z]+$/,
}